version: "3.9"

services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./content:/go/src/app/content:ro
    env_file:
      - .env
